version: '2'
services:
  redis: 
    image: 'bitnami/redis:6.0.16'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    #image: 'webdevops/php-apache:8.0-alpine'
    build: './docker/web/'
    ports:
      - '80:80'
      - '443:443' # 开放 https 需要的接口
    depends_on:
      - redis
    volumes:
      - './:/app'
    environment:
      - DB_DATABASE=pushdeer
      - DB_HOST=clouddb.com
      - DB_PASSWORD=thep@ssw0rd
      - DB_PORT=3306
      - DB_TIMEZONE=+08:00
      - DB_USERNAME=pushdeer
      - APP_DEBUG=false
      - GO_PUSH_IOS_TOPIC=com.pushdeer.self.ios
      - GO_PUSH_IOS_CLIP_TOPIC=com.pushdeer.self.ios.Clip
